ХНУРЕ:
  name: "Харківський національний університет радіоелектроніки"
  edu_programs:
    ПЗПІ:
      name_long: "Інженерія програмного забезпечення"
      department_gen: "Програмної інженерії"
      code: 121  # TODO = ПЗПІ is "F2" now
    КУІБ:
      name_long: "Управління інформаційною безпекою"
      department_gen: "Інфокомунікацій"
      code: 125
  subjects:
    БД: "Бази даних"
    БЖД: "Безпека життєдіяльності"
    ОІМ: "Основи IP-мереж"
    "ОПНJ": "Основи програмування на Java"
    ОС: "Операційні системи"
    ОТК: "Основи теорії кіл"
    ПП: "Проектний практикум"
    ПРОГ: "Програмування"
    СПМ: "Скриптові мови програмування"
    УФМ: "Українське фахове мовлення"
    Ф: "Філософія"
    ФІЗ: "Фізика"
