ХНУРЕ:
  name: Харківський національний університет радіоелектроніки
  edu_programs:
    ПЗПІ:
      name_long: Інженерія програмного забезпечення
      department_gen: Програмної інженерії
      code: 121  # TODO: change to F2?
    КУІБ:
      name_long: Управління інформаційною безпекою
      department_gen: Інфокомунікаційної інженерії ім. В. В. Поповського
      code: 125
  subjects:
    ODS: Основи Dаtа Sсіеnсе # NOTE: Eng O here
    ІМ: Іноземна мова
    АКтаК: Архітектура комп'ютера та комп'ютерних мереж
    АТСД: Алгоритми та структури даних
    БД: Бази даних
    БЖД: Безпека життєдіяльності
    ВДІТБ: Введення до ІТ-бізнесу # NOTE: all in UA
    ВМ: Вища математика
    ГТГ: Гіпертекст та гіпермедіа
    ДМ: Дискретна математика
    КДМА: Комп'ютерна дискретна математика
    КМ: Комп`ютерні мережі
    КЗВШ: Креативність з використанням штучного інтелекту
    ЛМВ: Людино-машинна взаємодія
    МОТДО: Методи оптимізаціі та дослідження операцій
    МС: Моделювання систем
    ОІМ: Основи IP-мереж
    ООП: Об'єктно-орієнтоване програмування
    ОП: Основи права
    ОПІ: Основи програмноі інженеріі
    ОПНJ: Основи програмування на Java
    ОПр: Основи програмування
    ОС: Операційні системи
    ОТК: Основи теорії кіл
    ПНП: Програмування на платформі .NЕТ
    ПП: Проектний практикум
    ПРОГ: Програмування
    СМП: Скриптові мови програмування
    ТЙтаМ: Теорія ймовірностей та математична # TODO: what?
    ТКП: Технології комп`ютерного проєктування
    УФМ: Українське фахове мовлення
    ФІЗ: Фізика
    ФІЛ: Філософія
    ФВС: Фізичне виховання та спорт